### ISSUE TITLE
Add NTP

### ISSUE THREAD

**Issue by NilzOS** [domneedham/pico-clock-green-python#18]
why not set the time via NTP ?

**Comment by domneedham** [comment]
I had thought about doing this, I am still yet to get my hands on a Pico W so that I can reliably test that it will work. Should make handling time changes much easier

As soon as I do, I will work on it.

**Comment by domneedham** [comment]
Yeah it is a good idea, will add a config option to set the users timezone and then can use NTP to set the time on clock start.

**Comment by domneedham** [comment]
#21
