### ISSUE TITLE
can you explain in details how load code on pico W

### ISSUE THREAD

**Issue by Hitesh-007** [domneedham/pico-clock-green-python#20]
please help me for this how load Pico green clock demo code on PICO

**Comment by domneedham** [comment]
First you need to flash MicroPython onto your Pico. Raspberry Pi documents how to do this well. 

You are best following the steps at: https://github.com/domneedham/pico-clock-green-python#instructions-linuxmac

If you are on Windows, I am not sure the best way to do this yet.

The whole install process really needs improving to be honest.

**Comment by Hitesh-007** [comment]
Hi Domneedham
   Thank you for your reply
I try using Raspberry pi buts it's not working
Can you explain in detail if possible
Display import error show
Thank you for your help

**Comment by Hitesh-007** [comment]
Hi
  please, Can you help me?

**Comment by domneedham** [comment]
To be honest, if you are not looking to code anything on this project anyway, you may be best using one of the C++ versions that are maintained by other people. They have a simpler install process :)

**Comment by Hitesh-007** [comment]
Hello
   I like your project and features it's looking awesome,
By the way I am waveshare FAR  engineer.
Thank you for replying.
